### ISSUE TITLE
Run all examples

### ISSUE THREAD

**Issue by fredRos** [bat/bat#100]
I was checking to see if all examples are run with  `make -C examples check` and realized that's not the case. I think all examples in `basic/*` are compiled and run.
But here are a few questions for @oschulz and @greenwald on the stuff in `examples/advanced/*`.

advancedGraphFitter
------------------------------

```
make[3]: Entering directory '/home/beaujean/workspace/bat/r6.04.10/examples/advanced/advancedGraphFitter'
make[3]: Nothing to be done for 'check'.
```
There is a test in that directory that is deactivated. @oschulz do you remember why? I fixed that one myself in #98 to test `BCGraphFitter`.

mvc
-----

Nothing exectued except `PASS: input.txt`. I thought that was on purpose. @kevin-kroeninger any chance you can check or clean up those examples? Or should we remove or deactivate that code? Do you know who uses the `mvc`?

rooInterface
----------------

`runRooInterface` is built but not executed. Bug?

**Comment by oschulz** [comment]
> There is a test in that directory that is deactivated. @oschulz do you remember why?

Some examples are still deactivated for `make check` because they were crashing at the time I integrated the examples into check. If they work reliably now, we should of course activate them again.

**Comment by fredRos** [comment]
After mvc was removed through #106 , the only remaining part is the roointerface. I refactored and activated the test in #113
