### ISSUE TITLE
remove mvc?

### ISSUE THREAD

**Issue by fredRos** [bat/bat#101]
I was just working on #77 and realized there's not much documentation on mvc. Nothing really comes up in the doxygen output because the comments that exist are not in doxygen format. In any case, they only give much more information than the name of the method that they come along with. I'm missing a bigger picture of what this is good for and how it is to be used. The examples don't provide much insight either. I don't know what it does so I don't want to maintain it.

We have had this discussion before but now we are getting serious. I vote for removing it from 1.0. It's not part of the core so we can add it back in later if there is documentation on it, presumably from @kevin-kroeninger . Any objections to removing `models/mvc` and `examples/advanced/mvc` now?

**Comment by oschulz** [comment]
If this isn't seriously used at the moment, I'm also in favour of removing it for now.

**Comment by greenwald** [comment]
I also vote to remove it until it can be cleaned up and documented.

Dan

On Wed, Nov 25, 2015, 19:47 Oliver Schulz <notifications@github.com> wrote:

> If this isn't seriously used at the moment, I'm also in favour of removing
> it for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bat/bat/issues/101#issuecomment-159698834>.
>
-- 
------------------------------------------------
Daniel Greenwald
Physik-Department E18
Technische Universität München
James-Franck-Str. 1
85748 Garching
Germany

daniel.greenwald@tum.de
tel   :  +49 89 / 289 12569
fax  :  +49 89 / 289 12570
