### ISSUE TITLE
make distcheck from out-of-source build

### ISSUE THREAD

**Issue by fredRos** [bat/bat#103]
As mentioned in #77, `make distcheck` fails from an out-of-source build directory when it comes to compiling the examples.

```
Making all in systematics
libtool: link: g++ -I../../../../src/.includes -I../../../../models/base/.includes -I../../../../models/mtf/.includes -I../../../../models/mvc/.includes -pthread -m64 -I/home/beaujean/.local/sw/root/linux-debian-8.0-x86_64/5.34.25/include/root -o .libs/runSystematics runSystematics.o  -L/home/beaujean/.local/sw/root/linux-debian-8.0-x86_64/5.34.25/lib/root ../../../../src/.libs/libBAT.so ../../../../models/base/.libs/libBATmodels.so ../../../../models/mvc/.libs/libBATmvc.so ../../../../models/mtf/.libs/libBATmtf.so -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMinuit -lMathMore -lRooFitCore -lRooFit -lRooStats -lFoam -pthread -Wl,-rpath -Wl,/home/beaujean/workspace/bat/r5.34.25/BAT-0.9.4.1/_inst/lib
g++: error: runSystematics.o: No such file or directory
Makefile:590: recipe for target 'runSystematics' failed
```

This is not critical but something nice to have. 

By the way, why does a simple `make` trigger buildling all examples none of the tests? Is that distinction necessary? If we want a long build, might as well build the unit tests. I'd imagine @greenwald prefers not building anything but the libraries.

**Comment by oschulz** [comment]
I'm not sure that `make distcheck` is supposed to work from an out-out-tree build directory.

**Comment by oschulz** [comment]
I did some more digging - apparently, some projects do support `make dist` (and I guess also `make distcheck`, by implication) from out-of-tree. This shouldn't have a high priority, as I can't see an important use case - but I'll try to fix this, at some point.

**Comment by fredRos** [comment]
Problem persists but it's not important. The main thing that should work is an out-of-source build, and that works fine.

> By the way, why does a simple make trigger buildling all examples none of the tests? Is that distinction necessary? If we want a long build, might as well build the unit tests.

the examples are part of the `all` target, the unit tests are part of `check` and thus not build
