### ISSUE TITLE
install on ubuntu

### ISSUE THREAD

**Issue by fredRos** [bat/bat#109]
get minimal set of root packages to make bat build. A user reported that even `root-system` wasn't enough because some header was missing

**Comment by oschulz** [comment]
The Debian/Ubuntu ROOT packages are way out of date anyhow. But CERN now provides ROOT binaries for Ubuntu 14.04: https://root.cern.ch/content/release-60410

The following packages are required to use those CERN ROOT binaries and to compile BAT on Ubuntu 14.04 (tested on a Vagga container): curl, libxext-dev, libxpm-dev, libglu-dev, libxft-dev build-essential, gfortran, python-dev, libxml2-dev.

**Comment by fredRos** [comment]
> The Debian/Ubuntu ROOT packages are way out of date anyhow

True, they are old but they are good enough to build bat. I spent the time to single out the packages. @oschulz it would be great if you could verify on your clean ubuntu version since I tested on my debian system and I don't have immediate access to a virgin ubuntu 

    sudo apt-get install libroot-graf2d-postscript-dev libroot-graf3d-g3d-dev libroot-math-foam-dev libroot-math-minuit-dev libroot-math-physics-dev libroot-math-mathmore-dev libroot-roofit-dev root-system-bin

**Comment by oschulz** [comment]
> True, they are old but they are good enough to build bat

Hm, for me it doesn't work: With the ROOT-5.34.14 included in Ubuntu 14.04 (tested in a Docker and a Vagga container), I get

    /usr/include/root/TH1.h: In constructor 'BCEfficiencyFitter::BCEfficiencyFitter(const TH1&, const TH1&, const TF1&, const string&)':
    /usr/include/root/TH1.h:134:21: error: 'virtual void TH1::Copy(TObject&) const' is protected
        virtual void     Copy(TObject &hnew) const;
                         ^
    BCEfficiencyFitter.cxx:53:24: error: within this context
         trials.Copy(fTrials);

**Comment by fredRos** [comment]
Interesting, I have 5.34.19 on debian jessie and it works. I will check tomorrow with the user who also got it to work. I thought he had ubuntu 14.04 but apparently he has a different system.

**Comment by fredRos** [comment]
Ok, he had mint with 5.34.14 and was using the master branch from Nov 23. A lot has changed since., so after updating he got the same error. 

Either I find a simple way to do without the `Copy` function, or I just update the instructions and require 5.34.19 as the minimum version.

**Comment by oschulz** [comment]
I guess the real question is, what is the oldest ROOT-5 version that we want to support? Let's decide on that - afterwards I'll also use that version for all ROOT-5-based BAT build tests.

**Comment by fredRos** [comment]
I say 5.34/14. This one is in Ubuntu 14.04 I have made sure it works with the current version in #110

**Comment by oschulz** [comment]
Ok, why not - I'll install ROOT-5.34.14 on my test machines, too.

**Comment by oschulz** [comment]
I did some more tests: I can't build ROOT-5.34.14 on Ubuntu-14.04, neither with the default options, nor with the options I usually use. The oldest version that still compiles is 5.34.20 - it's possible that the Ubuntu root-system -5.34.14 package includes some patches. Given that situation, I doubt we should still support a ROOT version that doesn't build on a current Linux distro - esp. as we'd have to regularly test with it.

**Comment by fredRos** [comment]
> can't build ROOT-5.34.14 on Ubuntu-14.04

I'm surprised. But now we made a lot of changes also make life easier for the users. I don't want to put a minimum of 5.34/20 into `configure.ac` because then it complains about 5.34.14 being old even though bat works with it. Obviously if you can't build root you will not try to compile bat. If root is already compiled, why exclude it? We were never that rigorous before, we allow 5.27.04 in the current master branch

I vote for being explicit in `INSTALL.md`:

```
we regularly test with 5.34/20 but bat 1.0 is known to work also with root 5.34.14 available in Ubuntu 14.04 and root 5.34.19 available in Debian Jessie
```

and in `configure.ac`, I put
```
REQUIRE_ROOT_VERSION([5.34.14])
```

Is that a good compromise?


The upcoming Ubuntu LTS has 5.34/30 so all is fine there
http://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=root-system
and we can bump the minimum version in half a year if we want.

**Comment by oschulz** [comment]
> Is that a good compromise?

Sounds good. Later on, when I move the automated testing to VM (resp. container) instances (I have some things in the works) I can test with 5.34.14.

**Comment by fredRos** [comment]
Great, then please have a look at the pull request #110, it should represent our consensus
