### ISSUE TITLE
Not using BCTrash

### ISSUE THREAD

**Issue by greenwald** [bat/bat#132]
We appear not to be using `BCTrash` where we should in `BCEfficiencyFitter` (and probably elsewhere in the `models/base` objects). Lots of ROOT objects are created in memory and not stored for later deletion.

Likewise, @fredRos, why are we not using `BCTrash` in `BCHistogramBase`?

**Comment by fredRos** [comment]
Seems to have been fixed in 0789179ef4, most objects  are created/trashed in `BCFitter` and not in its child classes
