### ISSUE TITLE
Model Manager::BayesFactor probably leads to wrong results

### ISSUE THREAD

**Issue by tquante** [bat/bat#135]
Dear Developers,

I am currently working with the BAT1.0_RC1 and I have noticed that the ModelManager return a BayesFactor of 1 if both ModelIntegrals are below 2.220446e-16. After looking into the code I noticed that this is based on the if statements which uses std::numeric_limits<double>::epsilon(). I wonder why this function is used, because this returns a double which is much larger than std::numeric_limits<double>::min() returns which returns 2.225074e-308. Are there any restrictions in this calculation which I miss? Hopefully you can help me, because it is impossible for me to get larger values than 2.220446e-16 for both models

Regards 
Thomas

**Comment by fredRos** [comment]
I can reproduce the problem if I modify `examples/advanced/polynomialFit/PolAsymm.cxx`:
```c++
double PolAsymm::LogLikelihood(const std::vector<double>& par)
{
...
    logl -= 50;

    return logl;
}
```
such that the evidence is around 1e-25.
