### ISSUE TITLE
Error band is empty in some cases

### ISSUE THREAD

**Issue by tquante** [bat/bat#137]
Dear Developers,

I have noticed that the error band is not filled correctly if the used model is added to a modelmanager. This can be reproduced by adding a modelmanager to the HistogramFitterExample changing hf to hf*
and adding it to the manger. The error band is not shown in the fit.pdf and the entries of a histogram obtained by 
 TH2* errorband_hist=hf->GetGraphicalErrorBandXY(0.9999); 
are zero as well as the Integral.

BAT Version: 1.0.0-RC1
ROOT Version: 6.04.10

Thanks for your help

Regards 

Thomas

**Comment by fredRos** [comment]
I can reproduce the empty error band: in `examples/basic/histogramFitter/histogramFitterExample.C`, replace 
```c++
    // perform fit
    hf.Fit();

    // calculate p values
    hf.CalculatePValueFast(hf.GetBestFitParameters());
    cout << "p value " << hf.GetPValue() << ", corrected for degrees of freedom " << hf.GetPValueNDoF() << endl;
```
with
```c++
    BCModelManager man;
    man.AddModel(&hf, 1.0);

    man.MarginalizeAll();
    man.FindMode();
```
