### ISSUE TITLE
p value degrees of freedom

### ISSUE THREAD

**Issue by fredRos** [bat/bat#141]
In code like this https://github.com/bat/bat/blob/master/models/mtf/BCMTF.cxx#L1110, we _correct_ a p value based on the degrees of freedom

``` c++
double BCMTF::CalculatePValue(const std::vector<double>& parameters)
{
    ...
    // create pseudo experiments
    static const unsigned nIterations = unsigned(1e5);
    fPValue = BCMath::FastPValue(observation, expectation, nIterations, fRandom.GetSeed());
    fPValueNDoF = BCMath::CorrectPValue(fPValue, parameters.size(), observation.size());

    return fPValue;
}
```

There are two issues: 
1. we don't know how the value of `parameters` is chosen. It might not be at the mode, so we can't just apply the degree-of-freedom correction,
2. if some parameters are fixed, we'd need to pass `GetNFreeParameters()` instead of `parameters.size()`. But maybe the parameters weren't fit at all.

Sounds to me like we cannot reliably do the correction, so we should not do this automatically. I propose to remove members like `fPValueNDoF`. Then we show in examples and the manual how the _user_ can correct it using `BCMath::CorrectPValue`

**Comment by greenwald** [comment]
I second the haircut.
