### ISSUE TITLE
assignment operators

### ISSUE THREAD

**Issue by fredRos** [bat/bat#142]
I looked through `BCModel`, `BCIntegrate`, `BCEngineMCMC`. None of them has an assignment operator but they have copy ctor and swap. So why no assignment? We had it before I suppose @greenwald removed them, what was the reason? In my opinion, we should implement them, of course with the copy-swap idiom.

**Comment by greenwald** [comment]
I think I added them and _you_ removed them, no?

**Comment by fredRos** [comment]
I remove the swap methods where they weren't needed. In any case, I will then reinstate the assignment operators

**Comment by fredRos** [comment]
Since all of  `BCModel`, `BCIntegrate`, `BCEngineMCMC` are abstract, you can't use the usual copy-swap implementation of `assignment=(BCIntegrate b) by value. Similarly the swap functions are fairly useless. We could offer a `Copy` function. In each derived class, it would have to call its parent's `Copy`.

**Comment by fredRos** [comment]
But in a non-abstract derived class, you can use copy-swap. For example, in `BCEmptyModel.h`:

```c++
class BCEmptyModel : public BCModel
{
public:
...
    BCEmptyModel& operator=(BCEmptyModel);
    friend void swap(BCEmptyModel& A, BCEmptyModel& B);

    // no data members
...
};
```
And in the implementation `BCEmptyModel.cxx`:

```c++
BCEmptyModel& BCEmptyModel::operator=(BCEmptyModel other)
{
    swap(*this, other);
    return *this;
}

// ---------------------------------------------------------
void swap(BCEmptyModel& a, BCEmptyModel& b)
{
    using std::swap;
    swap(static_cast<BCModel&>(a), static_cast<BCModel&>(b));
}
```

The compiler-generated copy ctor is fine as it just invokes `BCModel`'s copy ctor.

To  be clean, we'd have to do this in all our classes inheriting from `BCModel`. That would be a separate issue, though.

**Comment by fredRos** [comment]
This is a pain for a user. The implicitly generated copy ctor and copy-assignment operator for a user model should work fine. We can achieve that by implementing those operator for `BCEngineMCMC` etc. ourselves and get the exception safety with `try ... catch`. It's ugly but shields the trouble from the user
