### ISSUE TITLE
Print only 1D distributions

### ISSUE THREAD

**Issue by fredRos** [bat/bat#147]
With lots of parameters or observables, I'm happy with just the 1D marginals. We should split `BCEngineMCMC::PrintAllMarginalized` in two, one for 1D, one for 2D

**Comment by greenwald** [comment]
We already have the ability to turn 1d and 2d plotting on and off for all variables. (This is also a finer control, since you can also turn on and off individual variables or combinations of variables.) Wouldn't this be redundant with that?

**Comment by fredRos** [comment]
Oops, seems like somebody should write a manual :smile: 

in [`BCVariableSet.h`](https://github.com/bat/bat/blob/master/BAT/BCVariableSet.h#L218)
```c++
virtual void FillH2(bool flag)
```
