### ISSUE TITLE
GetBestFitParameters

### ISSUE THREAD

**Issue by fredRos** [bat/bat#149]
With parameters and observables, `BCIntegrate::GetBestFitParameters()` returns only the parameter values but `BCEngineMCMC::GetBestFitParameters()` returns the observable values as well. I don't see why, the latter should not return the observables., @greenwald what do you say?

``` c++
const std::vector<double>& BCIntegrate::GetBestFitParameters() const
{
    if (fBestFitParameters.empty() and !BCEngineMCMC::GetBestFitParameters().empty())
        return BCEngineMCMC::GetBestFitParameters();
    return fBestFitParameters;
}

 virtual const std::vector<double>& BCEngineMCMC::GetBestFitParameters() const
    { return fMCMCStatistics_AllChains.mode; }
```

**Comment by fredRos** [comment]
Sorry about the confusion, I hit a bug (PR coming) with value at mode = inf, then the observables weren't added. With that fixed, now the observable values at the mode are added even in `BCIntegrate` through [SetBestFitParameters](https://github.com/bat/bat/blob/master/src/BCIntegrate.cxx#L248). But why?

For  the name `GetBestFitParameters()`, I expect to get the parameters only, not the observables.

**Comment by greenwald** [comment]
I have no objection to separating the observables from the parameters in this situation.
