### ISSUE TITLE
libtool version mismatch

### ISSUE THREAD

**Issue by fredRos** [bat/bat#154]
_From a user by email_

I was trying to install Bayesian Analysis Toolkit on my laptop. I followed
INSTALL.md file. When I did make, I got the following error :-

```
thep@dinesh [17]make
make  all-recursive
make[1]: Entering directory `/home/dinesh/Downloads/BAT-1.0.0-RC1'
Making all in src
make[2]: Entering directory `/home/dinesh/Downloads/BAT-1.0.0-RC1/src'
make  all-am
make[3]: Entering directory `/home/dinesh/Downloads/BAT-1.0.0-RC1/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.
-I..    -pthread -std=c++11 -Wno-deprecated-declarations -m32 -msse
-mfpmath=sse -Wall -fPIC -I../BAT -I.includes
-I/home/dinesh/Downloads/root-6.04.12/include   -O2 -Wno-unknown-pragmas
-MT BCTH1Prior.lo -MD -MP -MF .deps/BCTH1Prior.Tpo -c -o BCTH1Prior.lo
BCTH1Prior.cxx
libtool: Version mismatch error.  This is libtool 2.4.4, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.4
libtool: and run autoconf again.
make[3]: *** [BCTH1Prior.lo] Error 63
make[3]: Leaving directory `/home/dinesh/Downloads/BAT-1.0.0-RC1/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/dinesh/Downloads/BAT-1.0.0-RC1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dinesh/Downloads/BAT-1.0.0-RC1'
make: *** [all] Error 2
```

**Comment by fredRos** [comment]
_by email_

I guess you downloaded the 1.0 release candidate tarball? What system
are you on?

The error message is quite self explanatory and it appears this has
nothing to do with BAT itself but rather with the autotools build system
that we use. And obviously you have a more recent version of libtool
than the person (i.e. the BAT release manager) that created the tarball.
I will try to find out what we can do to avoid this inconvenience in the
future. For now, a quick websearch suggests the following. In the BAT
directory, do

```sh
rm aclocal.m4
aclocal
autoconf
```

then continue with the usual

```sh
./configure # with same options as you used before
make
```

Do you still get the error? Obviously you need aclocal and autoconf
installed. You might since you have libtool.

**Comment by fredRos** [comment]
_by email_

I am using ubuntu 14.04. I am still getting the same error.

**Comment by fredRos** [comment]
strange, I tried to build the rc1 tarbal on ubuntu 14.04 and it worked fine. I have the autotools installed from the ubuntu repositories, aclocal 1.14.1, autoconf 2.69, libtool 2.4.2. How come you have libtool 2.4.4?

Another potential issue I see is that you compile for 32 bit (-m32 flag). We only test on 64 bit. Perhaps this causes trouble? How did you obtain or build root? Are you on a 32 bit system?

**Comment by oschulz** [comment]
I'll try on Ubuntu-16.04, to have a comparison

**Comment by oschulz** [comment]
I think the problem here is that the user in question is mixing two libtool versions.

BAT 1.0.0-RC1 builds and passes all tests on Ubuntu 16.04 (comes with libtool-2.4.6), with both ROOT-5 and ROOT-6.

Note: One needs to use the current "v5-34-00-patches" branch to build ROOT-5 on Ubuntu 16.04, due to GSL-2 (see https://sft.its.cern.ch/jira/browse/ROOT-7776).

**Comment by fredRos** [comment]
I agree,  there must be a mismatch

_by email_

I'm still surprised how you got libtool 2.4.4. From

http://packages.ubuntu.com/search?suite=all&arch=i386&searchon=names&keywords=libtool

I get these libtool versions for the various supported ubuntu versions for i386 (32 bit)


    precise (12.04LTS) (devel): Generic library support script
    2.4.2-1ubuntu1: amd64 i386
    trusty (14.04LTS) (devel): Generic library support script
    2.4.2-1.7ubuntu1: amd64 i386
    vivid (devel): Generic library support script
    2.4.2-1.11: all
    wily (devel): Generic library support script
    2.4.2-1.11: all
    xenial (devel): Generic library support script
    2.4.6-0.1: all 

There is no 2.4.4! So it seems to me you must have gotten libtool 2.4.4 from somewhere else and perhaps you still have libtool 2.4.2 installed which results in a conflict. Can you repeat the following steps, please?

```sh
$ which libtoolize
/usr/bin/libtoolize
$ libtoolize --version
libtoolize (GNU libtool) 2.4.2
$ locate libtoolize
/usr/bin/libtoolize
/usr/share/man/man1/libtoolize.1.gz
```

and tell me if you get the same output on your system?

**Comment by fredRos** [comment]
There was no more reply, I think this is a problem on the user's side
