### ISSUE TITLE
Manual Style

### ISSUE THREAD

**Issue by greenwald** [bat/bat#162]
Here we can store a list of style issues for the manual:

Choices to be made:
- "one" vs "you"

Choices I've made, and you must accept:
- we use the serial comma

**Comment by fredRos** [comment]
This kind of stuff belongs to the wiki, I moved it there
https://github.com/bat/bat/wiki/Manual-style

**Comment by greenwald** [comment]
The wiki doesn't have discussion. You added the entry as "you as opposed to one" --- however you appear to have used "one". Which one do you want?

**Comment by fredRos** [comment]
I want "you". I will go through and change it

**Comment by fredRos** [comment]
> The wiki doesn't have discussion.

we can continue the discussion here and keep the result in the wiki. That's easiest to keep track of
