### ISSUE TITLE
Use BCModel::PrintSummary to print results to a file without prefixes in v1.0

### ISSUE THREAD

**Issue by talismanbrandi** [bat/bat#167]
In HEPfit we would like to print the results of the MCMC using the BCModel::Summary into a separate file. Earlier this was possible with BCModel::PrintResults. Now BCModel::PrintSummary append "Summary:" to each line which we would like to avoid. I made some modifications to BCLog by adding a new log level called "results" to overcome this. The modifications are minor and can be found in this [commit](https://github.com/talismanbrandi/bat/commit/bda177dbf390861919568924ce725763e95a7b1b) in my fork of your repository. We would like to request the inclusion of this feature. I am also adding a sample output.

This is generated with:
`BCLog::OpenLog(("MonteCarlo_results" + JobTag + ".txt").c_str(), BCLog::results, BCLog::nothing);
 MCEngine.PrintSummary();`

MCEngine inherits from BCModel.

Also, notice in the output below scale factors and efficiencies are not printed properly. This happens even if I print to screen.

 Status of the MCMC
 ==================
 Convergence reached:                    no
 Number of chains:                       5
 Number of iterations per chain:         1000000
 Scale factors and efficiencies (measured in last %d iterations):
 Chain : Scale factor    Efficiency

[MonteCarlo_results.txt](https://github.com/bat/bat/files/235580/MonteCarlo_results.txt)

**Comment by fredRos** [comment]
After a "slight delay" of little under two years... sorry about that! I created a new PR to close this issue

Your solution was a bit hacky to replace `summary` with `results` only in a special case. And one would lose the option to fix the detail when printing. In ef9c532  I implemented a much simpler and more general solution: just turn off the prefix  with the new method `BCLog::SetPrefix(false);`

> Also, notice in the output below scale factors and efficiencies are not printed properly. This happens even if I print to screen.

I found the reason: in `BCEngineMCMC::PrintMarginalizationSummary`

```c++
            BCLog::OutSummary(" Chain : Scale factor    Efficiency");
            for (unsigned c = 0; c < fMCMCNChains; ++c)
                BCLog::OutDetail(Form("   %3d :       % 6.4g        %4.1f %%", c, fMCMCProposalFunctionScaleFactor[c][0], 100.*fMCMCStatistics[c].efficiency[0]));
```

so if your loglevel is not set to detail, you won't see the number in the output. I guess I should just not output the header.

**Comment by talismanbrandi** [comment]
Thanks for the fix!
