### ISSUE TITLE
Marginalized histogram names in the root file are stored by parameter/observable index and not their name

### ISSUE THREAD

**Issue by talismanbrandi** [bat/bat#170]
The marginalized histograms produced for the root file by the CreateHistograms method in BCEngineMCMC names the histograms with the parameter/observable index and not the name. While this might be a good idea in case someone forgets to give a name to the variable/observable, it would also be good to have the histogram names contain the name of the parameter/observable. I have made some modifications to this effect in this [commit](https://github.com/talismanbrandi/bat/commit/3b118cbfd2815a300381bf8a575b90af9fb95502). While this does not check if the SafeName() exists it works for us since we always give the parameters names. It would be nice if this could be included in v1.0 and/or subsequent versions.

**Comment by fredRos** [comment]
Fixed by #238
