### ISSUE TITLE
GetSmallestInterval in BCH1D gives wrong interval

### ISSUE THREAD

**Issue by talismanbrandi** [bat/bat#172]
I fixed what seemed like a bug in BCH1D where it was sometimes giving an extra interval which was outside the region. 

I have created a commit [here](https://github.com/talismanbrandi/bat/commit/0613d16b6697d34f86357edd7fc3bd02172d57ce)

Also I would like to raise a concern about not using fBandOvercoverage in line:437:

std::vector<std::pair<double, double> > bounds = GetSmallestIntervalBounds(masses);

which would make overcoverage default to true.

thanks
Ayan

**Comment by fredRos** [comment]
A user reported on bat 1.0rc1 that 

> I encountered concerns the function "GetSmallestIntervalSize" as it always only returns 0, no matter which histogram i tried with.

**Comment by talismanbrandi** [comment]
I don't see where "GetSmallestIntervalSize" is used. We have not used it directly from HEPfit and it seems that BAT does not use it either. However there was a bug which I fixed. I think it works now. Look [here](https://github.com/talismanbrandi/bat/commit/c2c3a232592a45f747e3092ac071b97a4c18ba8b).
