### ISSUE TITLE
BCPrior::GetBCH1D() returns an empty histogram

### ISSUE THREAD

**Issue by tquante** [bat/bat#175]
Dear Developers,

I would like to save the prior information by storing the corresponding prior histogram. Unfortunately the following code snipped results in an empty histogram with root 6.04.02:

``` c++
BCGaussianPrior *p=new BCGaussianPrior(5,1);
TH1D *hist=new TH1D("testhist","testhist",200,0,10);
BCH1D test=p->GetBCH1D(hist,"test");
TCanvas c("c1");
test.Draw();
```

The prior itself is valid and calling

``` c++
std::vector<double> x(1,5)
p->GetPriorForRoot(5,nullptr);
```

results in a finite value. By looking at the code I have no clue why the function is not working. It seems like the TF1 function passed to `TH1::Add` in `BCPrior::GetBCH1D()` returns zero all the time, which seems strange because it uses `GetPriorForRoot()` as function ptr.

Best Regards

Thomas

**Comment by fredRos** [comment]
First of all, I apologize for the extremely slow response, I didn't have time to look at BAT issues for a few months. 

> save the prior information

Did you just want to draw what it looks like? For this purpose, use `BCPrior::FillHistogramByCenterValue` or `BCPrior::FillHistogramByIntegral`. The snippet is

```c++

TCanvas c("c1");
BCGaussianPrior *p=new BCGaussianPrior(5,1);
TH1D *hist=new TH1D("testhist","testhist",200,0,10);
p->FillHistogramByCenterValue(hist);
hist->Draw();
```
which gives

![test](https://cloud.githubusercontent.com/assets/1833693/19309848/9d7cb648-9087-11e6-98ec-2e09bc88c8b2.png)

I looked into the code and I can't figure out why it doesn't work through `Add`ing the TF1. The same thing is done in `BCModel::PrintKnowledgeUpdatePlots` and it works fine there... :disappointed:
