### ISSUE TITLE
build error: sed -i

### ISSUE THREAD

**Issue by fredRos** [bat/bat#18]
*received by email*:

Dear All,

I am a new user of BAT. I try to install BAT on my laptop. But it fails. Could you tell me how can I install BAT on my laptop correctly?

OS   version: Mac OS X 10.9.5
root  version: 6.02.02 (installed at /Users/x/Prog/root-6.02.02)
BAT version: 0.9.4

In terminal, 

./configure --with-rootsys=/Users/x/Prog/root-6.02.02/
make

then the following errors are displayed.

... ...
/usr/bin/sed 's|\$clingAutoload\$\([^/""]\+/\)*|$clingAutoload$'BAT'/|; /.*DICTPAYLOAD(.*/,/.*)DICTPAYLOAD.*/ s|#include "\([^/"]\+/\)*\(.*\)"|#include |' -i libBAT_rdict.cxx
sed: -i: No such file or directory
// Do NOT change. Changes will be lost next time file is generated
... ...
make[2]: *** [libBAT_rdict.cxx] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

The log of configure and make command are attached.

I search the sed command on Google and I find the usage of this command is different between linux and mac (see the link for more details). I don't know if this is the reason why the installation fails in my laptop.

Thank you for your time.

Best Regards,

**Comment by greenwald** [comment]
I know there is an issue with sed and single quotes (') versus double quotes (") when using $-prefixed variables inside a script. Did we write the sed line or is it part of ROOT 6?

**Comment by fredRos** [comment]
It is our code, but it seems to be due to a very old version of sed on his mac. I created a patch branch at https://github.com/bat/bat/tree/sed
I can build it fine on my ubuntu machine with sed 4.2.2, but we need mac users to test it as well before I merge it into the main branch

**Comment by boveia** [comment]
Tested and found it needs `sed -i ''` instead of `sed -i''`

**Comment by ideefixdajoka** [comment]
I can confirm this. The bugfix with `sed -i ''` instead of `sed -i''` works fine on a Mac version 10.9.5

**Comment by fredRos** [comment]
It is fixed in 0e21ebf31730053fbed17e32319ad53843a6c2de. To be compatible between mac and linux, we now avoid `sed -i` and use tmp files instead

**Comment by fredRos** [comment]
And I turned this into a bugfix release https://github.com/bat/bat/releases/tag/v0.9.4.1
