### ISSUE TITLE
bat-project script produces incorrect Makefile

### ISSUE THREAD

**Issue by Rob-MFn-Fletcher** [bat/bat#196]
I have installed BAT-0.9.4.1 following all instructions. I then setup a skeleton project using the command:

    `bat-project MyProject MyModel`

This produces the files: 
 - Makefile  
 - MyModel.cxx  
 - MyModel.h  
 - runMyProject.cxx

If you run 'make' it returns the error:

    'make: *** No rule to make target `runMyModel.o', needed by `runMyModel'.  Stop.'

This is due to the line in the Makefile:

    CXXSRCS      = \
        runMyModel.cxx MyModel.cxx

As you can see runMyModel.cxx should be runMyProject.cxx. Changing this makes it work fine. I guess there is just a small error in the generation of the Makefile.

**Comment by fredRos** [comment]
Thanks for the report. 
This has already been fixed on master, please consider using the master branch
