### ISSUE TITLE
reiterations or self-adapting figure range

### ISSUE THREAD

**Issue by DingXuefeng** [bat/bat#197]
Hi,

Is there features that adjust the plotting range to be +/- 99.9% CI (or +/- 5 sigma) ?

we can do re-iterations or just adjust the plotting range. currently I need to adjust the range of fit parameters by hand and this is not convenient..

[var_kappa_p20t27_correlation_newmodel.pdf](https://github.com/bat/bat/files/645520/var_kappa_p20t27_correlation_newmodel.pdf)

**Comment by greenwald** [comment]
Hi,

There are a few ways you can achieve what you want (depending on exactly what you mean).

1. If you only want to change the visible range of the drawing of the histograms (but not their ranges or binning), you can get the `BCH1D` and `BCH2D` objects from your model and draw them each to a `TCanvas` yourself, and then manipulate the visible ranges using the standard ROOT functions or GUI (if you save the `TCanvas`).

2. a. If you want to change the range of the histograms themselves (or their binning), then you can read in the BAT output and redraw with changed binning. There is an example demonstrating this in `examples/basic/rootOutput`: `readRootOutput.cxx` uses a `BCEmptyModel` to open a `.root` file containing a BAT MCMC tree and then immediately calls `Remarginalize()`, which loads the samples form the `TTree` in the file and fills them into the histograms. To change the binning, after calling the constructor and before calling `Remarginalize()`, access the parameters (just as you would in your model---`BCEmptyModel` loads them for you) and change their limits. Then call the usual print functions. (If you want to automate the ranges to be the +-5sigma region, you'll need to `Remarginalize()`; then query the model for the information about the credibility intervals; then change the ranges accordingly; and then `Remarginalize()` again.)

   b. You can also do this in the same program that runs the original analysis. After you `MarginalizeAll(...)`, change the parameter limits or binning (using information from the output concerning the credibility intervals) and then call `Remarginalize()`. But if you are saving to file, I would recommend the version above instead.

3. If you set conservatively large ranges for parameters and just want to shrink the ranges down to where the posterior actually resides, then you can use the member function `SetRescaleHistogramAfterPreRun()`, which will use upper and lower bounds learned during the pre-run to set the range for the histogram (filled during the main run). The range is enlarged from the bounds by a factor set by `SetHistogramRescalingPadding(double)`. Beware this method sometimes can cut off part of your posterior, if the pre-run hasn't seen the whole area of your posterior (you can increase the minimum number of iterations in the pre-run to try to prevent this).

4. You can read in the `TTree` yourself in standard ROOT and fill the results into your own histogram. With this histogram you can either
  a. Draw it without the pretty graphics of BAT. Or
  b. Create a standalone `BCH1D` (or `BCH2D`) from your histogram and draw that to a `TCanvas`. This will allow to use all the nice graphics of BAT.
