### ISSUE TITLE
Examples not drawn on canvas

### ISSUE THREAD

**Issue by fredRos** [bat/bat#208]
[by email]
Dear authors,

I’m using ROOT 6.08/00 under mac OS X and I’ve downloaded and installed BAT1.0.0 from the BAT-1.0.0-RC1.tar.gz file.

I’ve started to run the basic examples to check if everything was running smoothly. I’ve realized that the MACROS run, I’ve tried the graphFitterSimpleExample.C and the efficiencyFitterExample.C, and everything seems to be working with the exception of the canvas Drawing, the pdf is generated though.

I jus t get the following warnings:

```

/Users/jorge/Downloads/BAT-1.0.0-RC1/examples/basic/histogramFitter/histogramFitterExample.C:33:56: warning: macro expansion producing 'defined' has undefined behavior
     [-Wexpansion-to-defined]
#if defined(__MAKECINT__) || defined(__ROOTCLING__) || COMPILER
                                                      ^
/Users/jorge/Downloads/BAT-1.0.0-RC1/examples/basic/histogramFitter/histogramFitterExample.C:31:20: note: expanded from macro 'COMPILER'
#define COMPILER (!defined(__CINT__) && !defined(__CLING__))
                  ^
/Users/jorge/Downloads/BAT-1.0.0-RC1/examples/basic/histogramFitter/histogramFitterExample.C:33:56: warning: macro expansion producing 'defined' has undefined behavior
     [-Wexpansion-to-defined]
/Users/jorge/Downloads/BAT-1.0.0-RC1/examples/basic/histogramFitter/histogramFitterExample.C:31:42: note: expanded from macro 'COMPILER'
#define COMPILER (!defined(__CINT__) && !defined(__CLING__))

```

Could you please let me know what may be the problem?

**Comment by fredRos** [comment]
[by email]
I’ve run make check and I got some errors …

Please find the log file of the test. I’m running BAT on mac osx EL Capitan.

I guess it doesn’t find libCore

```
========================================
   BAT 1.0.0-RC1: test/test-suite.log
========================================

# TOTAL: 10
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  10
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test
==========

dyld: Library not loaded: @rpath/libCore.so
  Referenced from: /Users/jorge/Downloads/BAT-1.0.0-RC1/test/.libs/test.TEST
  Reason: image not found

FAIL: BCAux
===========

dyld: Library not loaded: @rpath/libCore.so
  Referenced from: /Users/jorge/Downloads/BAT-1.0.0-RC1/test/.libs/BCAux.TEST
  Reason: image not found

...
```

**Comment by fredRos** [comment]
The rpath issue on os sierra is known, see #186 . We have a fix but it is still in testing by @oschulz: is it ready to merge into master now?

The canvas drawing seems to be a new issue, I presume related to the root version.

The warnings regarding macro expansion. are new too, which compiler and version do you use?

**Comment by jorgefdm** [comment]
thanks for the reply. I read the rpath issue on sierra, however my system is el capitan.

My compiler is clang-800.0.42.1.

**Comment by fredRos** [comment]
I'm not sure why for some users the rpath issue only crops up with sierra, while other noticed it with el capitan, when Apple introduced this "feature" https://github.com/bat/bat/issues/186#issuecomment-260472159 Have you installed typical linux software that may rely on `[DY]LD_LIBRARY_PATH`?

**Comment by jorgefdm** [comment]
Yes I have. I thought ROOT relied on LD_LIBRARY_PATH ...

 I also have installed xerces-c-3.1.1 and most probably many more others, but they were installed before this feature. ROOT I had installed it with my current system.

**Comment by fredRos** [comment]
I could reproduce the warnings with clang 3.8 and send a PR to fix that.

**Comment by fredRos** [comment]
Both the fix due to the macro expansion and rpath on mac os are now in master. We are now looking into the ROOT plotting issues

**Comment by fredRos** [comment]
We have checked with root 6.08.06 and 6.09.02, the latest versions available for download today on https://root.cern.ch/downloading-root The canvas drawing worked with both versions on the histogramfitter example. May I suggest you update root? I suspect that there is a different issue than root that prevents the canvas drawing on your system but I"m certain it has nothing to do with bat. Did you perhaps run root in batch mode?
