### ISSUE TITLE
1D histogram style in current root

### ISSUE THREAD

**Issue by fredRos** [bat/bat#213]
![1d](https://cloud.githubusercontent.com/assets/1833693/25987911/2982da4a-36f6-11e7-87b7-341fbdbaa2fb.png)

This is the first 1D marginal from the histogram fitter example but it applies to the other examples as well. we don't want points and error bars. Especially the points on the x axis are disturbing. Apparently the defaults changed. I created this plot with root 6.09.02 but I saw it before in 6.08 as well. 
@greenwald you know the plotting part best, could you please have a look?

**Comment by oschulz** [comment]
Fixed by #221.
