### ISSUE TITLE
Properly set log-flat prior 1/x

### ISSUE THREAD

**Issue by luigipertoldi** [bat/bat#214]
How can I properly set a log-flat prior (thus a 1/x prior)? I get a segmentation fault when trying to build the knowledge update plots with my code. To provide a MWE I modified `examples/basic/poisson/PoissonModel.cxx`:

```cpp
AddParameter("lambda", 0., 7., "#lambda"); // index 0
TF1 f("logflat", "1/x", 1, 2);
GetParameter("lambda").SetPrior(new BCTF1Prior(f));
```
and got, obviously:
```
Error in <GSLError>: Error 11 in qags.c at 543 : number of iterations was insufficient
Warning in <TF1::IntegralOneDim>: Error found in integrating function logflat in [0.000000,7.000000] using AdaptiveSingular. Result = 699.473515 +/- 9.350560  - status = 11
```
So I slightly modified the definition of `f`:
```cpp
TF1 f("logflat", "1/(x+1E-10)", 1, 2);
```
but then got `[1]    32367 segmentation fault (core dumped)  ./runPoissonCounting` when trying to
```cpp
m.PrintKnowledgeUpdatePlots("kup.pdf");
```

**Comment by luigipertoldi** [comment]
Anyway, this was a stupid question, there are a lot of different ways to address the problem avoiding integration issues. I should have think about this a little bit more.

**Comment by fredRos** [comment]
I agree that a log-uniform prior is useful and that we should offer it. Apparently the real issue is that so far the end points of the prior range were sane but with 1/x at x=0, we have a divergence. I wonder if we should

**Comment by luigipertoldi** [comment]
I'm not sure, but I think there's something wrong in `PrintKnowledgeUpdatePlots` related to integral-divergent priors. I tried to set a prior π(x) = x for a parameter in [0,1] and then the program crashed when trying to build knowledge-update plots. Same for π(x)=1/(1+x).

**Comment by luigipertoldi** [comment]
Same behavior with `TF1 f("mygauss", "exp(-(x-4)^2)", 1, 2);`. I'm trying this on the PoissonCounting example.

**Comment by luigipertoldi** [comment]
Now I see that there's a class named `BCTF1LogPrior`. In principle this
```cpp
this->GetParameter(0).SetPrior(new BCTF1LogPrior("1",0,1));
```
should be equal to this
```cpp
this->GetParameter(0).SetPrior(new BCTF1Prior("1/x",0,1));
```
right? The first one actually does not produce crashes during the execution, however the knowledge-update plot still reports a flat prior...

**Comment by luigipertoldi** [comment]
I tried with version 0.9.4.1 and everything seems to work, even with π(x)=1/x in [0,1].
