### ISSUE TITLE
Option to not monitor correlations for observables?

### ISSUE THREAD

**Issue by mkbugge** [bat/bat#226]
Hi,

I have recently added about 100 observables to my analysis, and the resulting large number of 2D correlation histograms presents some issues, like:

* Memory usage if the number of bins is increased for each observable
* Size of PDF file from "printAllMarginalized" and time it takes to generate this file
* Readability of correlation matrix and correlation plot (for the latter, I guess include_observables = false will do the trick, but no such option on the former)
* Analysis slows down, presumably because of filling all the 2D histograms?

So therefore I was wondering if there is some switch to turn off the 2D histograms for observables?

Cheers,
Magnar

**Comment by mkbugge** [comment]
OK, I found the BCVariable::FillHistograms function, so that's pretty much what I need.

**Comment by greenwald** [comment]
There are also several functions for fine control of what histograms are saved:
```cpp
SetFlagFillHistograms(bool flag_1d, bool flag_2d);
SetFillHistogramParPar(...);
SetFillHistogramParObs(...);
SetFillHistogramObsObs(...);
```

The first will let you turn off all 2D histograms (storage and output). Unfortunately there's no function that just turns off all observable 2D histograms. But the last three functions will let you toggle individual 2D histograms. Looping through the observables, you can affect what you want:

```cpp
BCModel M;
for (unsigned i = 0; i < M.GetNObservables(); ++i)
    for (unisgned j = i + 1; j < M.GetNObservables(); ++j)
        M.SetFillHistogram(i, j, false);
```
