### ISSUE TITLE
Too many <TH2D::GetBinWidth> errors

### ISSUE THREAD

**Issue by rdisipio** [bat/bat#227]
Hi,

  I recently switched to a new version of BAT I checked out from the GIT repository. In my code, I call the function  PrintKnowledgeUpdatePlots("file.pdf) to save one file the updated posteriors. However, the terminal output get swamped by errors like these:

```
Error in <TH2D::GetBinLowEdge>: Invalid method for a 2-d histogram - return a NaN
Error in <TH2D::GetBinLowEdge>: Invalid method for a 2-d histogram - return a NaN
Error in <TH2D::GetBinWidth>: Invalid method for a 2-d histogram - return a NaN

```
Since I'm generating O(1000) plots, this is very annoying. Is this a known bug?

Cheers,
Riccardo

**Comment by DmytroLevit** [comment]
Its a root bug which was recently already fixed in the master branch. So it will take some time to appear in the stable root builds. If you need it now, then just recompile root from git.

**Comment by fredRos** [comment]
@rdisipio Which version of root did you use when the error occured?

**Comment by rdisipio** [comment]
Hi,

  I'm setting up ROOT 6.10/04 and gcc 620_x86_64_slc6 on lxplus. Btw, I control my BAT model using a python script (python-2.7.13) instead of the usual C++ program presented in the examples (run-xyz.cxx).

Cheers,
Riccardo
