### ISSUE TITLE
roostats install from brew not recognised

### ISSUE THREAD

**Issue by matthewkenzie** [bat/bat#23]
Dear experts,

I am trying to install BAT on my local mac machine. I would like to be able to use the roofit and roostats interface with BAT and so have done a ./configure --enable-roostats. I get the following error:

checking whether ROOT version >= 5.27.04... yes
checking whether ROOT is compiled with MathMore support... no
checking for root-config... (cached) /usr/local/opt/root/bin/root-config
checking whether ROOT is compiled with RooFit/RooStats support... yes
checking whether ROOT is compiled with MathMore support... no
configure: error: ROOT was compiled without RooFit support.
				Recompile ROOT or provide path to different version.

I used brew to install root which I believe under the hood does (for ROOT) ./configure macosx --all and I have for example header files in $ROOTSYS/include/root/Math and $ROOTSYS/include/root/RooStats

Any ideas how to proceed?

Cheers,

Matt

**Comment by matthewkenzie** [comment]
Apologies I have solved this issue by including MathMore in my root install. This has been resolved.

**Comment by fredRos** [comment]
I wish all issues solved themselves :smile:
