### ISSUE TITLE
Histograms and ROOT memory management

### ISSUE THREAD

**Issue by fredRos** [bat/bat#230]
in #166 a general "feature" of ROOT caused problems. If there is `TFile` open, as it happens in many of the examples, many (but not all?) `TH*` histograms that we create in BAT are automatically registered with the file and deleted when the file is closed. But most histograms should be deleted by us unless it's a factory function. But within the BAT library we cannot know whether a user has a `TFile` open or not. To avoid guessing, I propose that we keep all our histograms out of ROOT's control. Here are the options:

## On existing histogram

    h->SetDirectory(0); 

after creating. This is simple but still gives a warning on the command line if a histogram of the same name is created again because ROOT doesn't check if we deleted it already.

## During histogram creation
 
     TH1::AddDirectory(kFALSE); 

```cpp
    TH2D *hist_uncbandexp;
    {
        // don't let ROOT manage these hists
        const bool oldDirectoryStatus = TH1::AddDirectoryStatus();
        TH1::AddDirectory(false);

        hist_uncbandexp = new TH2D(Form("UncertaintyBandExpectation_%s_%d", GetSafeName().data(), channelindex), "", hist.GetNbinsX(), &a[0], 1000, minimum, maximum);

        TH1::AddDirectory(oldDirectoryStatus);
    }

```

This approach fixed #166 but it is cumbersome. And there dozens other places where histograms are created. Is there a standard way of handling this? I tried to implement a macro to wrap around the constructor of the histogram but couldn't come up with something manageable. Other constructors may take 1 or 4 or n arguments... in C++11, variadic templates come to mind but we want to restrict to C++03. 

## Global

    TH1::AddDirectory(kFALSE); 

I tried to call this during static start up but ran into a crash on the `mtf/ensemble` example in the `BCMTF::PrintStack` function. Setting it globally might confuse users that rely on the standard ROOT behavior, so I'd prefer a local solution.

@oschulz @greenwald @daritter @dvandyk Any suggestions?

**Comment by daritter** [comment]
You can make it a bit less cumbersome with a guard object

```c++
class RootSideEffectGuard {
public:
  RootSideEffectGuard(): m_directory(gDirectory) {}
  ~RootSideEffectGuard() { gDirectory = m_directory; }
private:
  TDirectory* m_directory;
};
```

and then

```c++
TH2D *hist_uncbandexp;
{
  RootSideEffectGuard root_guard;
  hist_uncbandexp = new TH2D(Form("UncertaintyBandExpectation_%s_%d", GetSafeName().data(), channelindex), "", hist.GetNbinsX(), &a[0], 1000, minimum, maximum);
}
```
or just put the guard once in all functions which create histograms

```c++
void foo() {
  RootSideEffectGuard root_guard;
  ...
  TH2D* hist_uncbandexp = new TH2D(Form("UncertaintyBandExpectation_%s_%d", GetSafeName().data(), channelindex), "", hist.GetNbinsX(), &a[0], 1000, minimum, maximum);
  ...
}
```

**Comment by fredRos** [comment]
"Upvoted" @daritter answer

**Comment by oschulz** [comment]
BAT must *not* change global ROOT settings (e.g. via `TH1::AddDirectory(kFALSE)`).

**Comment by oschulz** [comment]
The cleanest way, IMHO, of creating a "standalone" ROOT histogram is via the default constructors, setting name and binning after creation.

**Comment by fredRos** [comment]
How does a default constructor change the issue that ROOT registers histograms and deletes them?  I noticed it in `examples/mtf/ensembleTest.C`

```c++
    // free memory
    delete file;

    // free memory
    delete m;
```

Because the file is deleted before the model, the files deletes histograms and then in the model dtor delete is called again leading to a segfault. As library authors, we have no way of knowing in what order users delete a file and the model, or if there is a file at all. Keeping ROOT from registering histograms is the only way I see to avoid segfaults apart from not using ROOT with its counterintuitive memory management

**Comment by daritter** [comment]
Yes, calling the default constructor and then setting the properties would work but is also not very convenient. The default constructor does not register a histogram and sets its internal directory pointer of the histogram to 0

The same affect can be achieved by setting `gDirectory=0` during the time histograms are created and this has the added benefit that it also protects against accidental `gDirectory` changes (for example when opening/closing a `TFile`).

---
Btw you can create a variadic macro

```c++
#define CREATE_HIST(type, name, ...)  \
  type* name = 0; \
  { \
    RootSideEffectGuard root_guard;  \
    name = new type(__VA_ARGS__); \
  }

void foo() {
  CREATE_HIST(TH1D, myhist, "name", "title", 100, -5, 5);
  myhist->Draw();
}
```

But I would not recommend that, it does not help code transparency.

**Comment by fredRos** [comment]
@oschulz Ok, just saw your comment in #229 . Where is the behavior documented that the default ctor doesn't register a histogram? ROOT drives me mad. In the  [TH1 docs](url), it doesn't say

**Comment by dvandyk** [comment]
@fredRos According to the sources, the TH1 default constructor calls the TNamed default constructor, which calls the TObject default constructor. Nowhere in that chain does registration happen. So to make @oschulz happy, you could use an adapter ```make_histogram``` or some such, which calls the default ctor and then changes the ```TH1```'s properties after construction, just as the specialized constructor would do.

All in all this remains a very ugly business, and is very error prone. Personally, I would prefer @daritter's solution. However, I'm unsure if ROOT tries to be clever about multi-threaded access to ```gDirectory```!

**Comment by daritter** [comment]
ROOT does not anything clever with `gDirectory` ... yet. `TFile` and `TDirectory` happily change this global variable without any protection.

But yes, my solution only works reliably for single threaded applications, as does the whole `gDirectory` concept ...

**Comment by oschulz** [comment]
> Where is the behavior documented that the default ctor doesn't register a histogram?

Nowhere (it's ROOT) - found out by myself a while ago. But it makes perfect sense - using the default ctor, the histogram doesn't have a name, so ROOT can't register it. :-)

**Comment by daritter** [comment]
slightly unrelated ROOT bashing below ...

> using the default ctor, the histogram doesn't have a name, so ROOT can't register it. :-)

... unless the rootrc setting `Root.ObjectStat` is set to 1 in which case ROOT will register all `TObject` instances in a global hash map and remove them in the destructor. This slows down code execution significantly and it is a joy to debug when the code is very slow for one specific user ... :skull_and_crossbones:

**Comment by fredRos** [comment]
I just vaguely remembered ROOT doing unconventional business with object management. But now that I see what it does exactly, it's almost absurd.

So it seems the thread-safe thing is to create a histogram using the default ctor. It seemed also that the copy ctor doesn't register a histogram (who knows why?). But how am I then to set the other properties like binning, name etc? @oschulz do you have example code in mind?

**Comment by oschulz** [comment]
When I built databricxx, I ended up with this solution:

https://github.com/databricxx/databricxx/blob/4263040b0aed371a78c066ff6f299efc11786d66/src/WrappedTObj.h

Note the function `releaseFromTDirIfAutoAdded(newObj)`. So while the object creation is not thread-safe, the created objects (and copies thereof) are. A `WrappedTObj` can be put in `std::vector`, copied, passed around, etc. And one can create it with the standard (e.g.) `TH1F` ctor parameters (they get forwarded).

As far as the default ctor method is concerned, I use that in "ROOTFramework.jl"
 (https://github.com/JuliaHEP/ROOTFramework.jl/blob/1f09d8741e84cf7d035db80e90274f6b6f94dc16/src/thxx.jl): The code mainly uses `hist->SetNameTitle(...)` and `hist->SetBins(...)`.

**Comment by daritter** [comment]
@oschulz there's only one drawback with the `releaseFromTDirIfAutoAdded(newObj)` approach: If there is already a histrogram with the same name in `gDirectory` ROOT will delete the previous one on construction of `newObj` and leave the user with a dangling pointer to a no longer existing object. This can be minimized by choosing horribly complex histogram names but ...

**Comment by oschulz** [comment]
@daritter, yes, I know, it's not perfect ... the clean way, in my opinion is to use the default ctor. At least I thought so until you read your posting about `Root.ObjectStat` - but I guess little can be done about that, and maybe we can hope that sane people won't use it. ;-)

**Comment by fredRos** [comment]
We have a couple of `h->Clone()` calls in the code, some set the name directly with `h->Clone(name)`. So does this register a histogram or not?

**Comment by fredRos** [comment]
Answering my own question: yes, they are registered, too, if `gDirectory` is set. But I found that internally this delegates the work to 

```c++
TObject *TDirectory::CloneObject(const TObject *obj, Bool_t autoadd /* = kTRUE */)
```

Inside `TH1.cxx`, I found this gem that shows how to clone but not register the object

```c++
      TH1 *hExpt = (TH1*)(gDirectory ? gDirectory->CloneObject(this,kFALSE) : gROOT->CloneObject(this,kFALSE));
```
This is not pretty either but it does the trick for clones in one line

```c++
TH1* hnew = static_cast<TH*>(gROOT->CloneObject(h, false)));
```

**Comment by oschulz** [comment]
> @daritter: `gDirectory = null`

Yes, that's also a good way. Some ROOT developer once told me that `gDirectory` is threadsafe, in principle - but I think it's thread-safety has to be enabled first, somehow.

One can use a guard object (like you suggested earlier, or like this one: https://github.com/databricxx/databricxx/blob/4263040b0aed371a78c066ff6f299efc11786d66/src/Bric.h#L188) or enclose things with `try`/`finally` to safely reset `gDirectory` after object creation.

**Comment by fredRos** [comment]
I think the guard approach is the best as it allows us to deal with creation, copying, and cloning in a uniform way. I will try it out and create a PR

**Comment by fredRos** [comment]
I tried this out. The guard works nicely for constructing objects directly but not with cloning. The output of a unit test

```
Fatal in <TList::Clone>: No gDirectory set
aborting
...
#5  0x00007f4a5461fc51 in TObject::Fatal(char const*, char const*, ...) const () from /home/beaujean/.local/sw/root/linux-ubuntu-16.04-x86_64/6.09.02/lib/libCore.so
#6  0x00007f4a5461fdcc in TObject::Clone(char const*) const () from /home/beaujean/.local/sw/root/linux-ubuntu-16.04-x86_64/6.09.02/lib/libCore.so
#7  0x00007f4a546703ee in TCollection::Clone(char const*) const () from /home/beaujean/.local/sw/root/linux-ubuntu-16.04-x86_64/6.09.02/lib/libCore.so
#8  0x00007f4a52f4f483 in TH1::Clone(char const*) const () from /home/beaujean/.local/sw/root/linux-ubuntu-16.04-x86_64/6.09.02/lib/libHist.so
#9  0x00007f4a54ae211b in BCHistogramBase::SetHistogram (this=0x7ffdc3567440, hist=0x1380600) at ../../src/BCHistogramBase.cxx:201
...
```

From the source and the doc string of [TObject::Clone](https://root.cern.ch/doc/master/classTObject.html#a4696036d44dcbe28970a13b8f4e5d6b2) I can see that it doesn't do anything w/o a `gDirectory`. 

So I'm going with this and the tests pass 

```c++
template <class T>
    T* OwnClone(const T* o)
{
    return static_cast<T*>(gROOT->CloneObject(o, false));
}
```
