### ISSUE TITLE
efficiencyfitter example plot

### ISSUE THREAD

**Issue by fredRos** [bat/bat#233]
Here is what I get with 416c7487a The labels are off and some data points near x=100 are at 0. This doesn't look right
[fit.pdf](https://github.com/bat/bat/files/1840920/fit.pdf)

**Comment by greenwald** [comment]
I get the same with ROOT 6.12/06, plus a segfault and a whole bunch of canvases popping up.

**Comment by greenwald** [comment]
Addressed by #247
