### ISSUE TITLE
--enable-parallel flag prevents libcuba.a to be found

### ISSUE THREAD

**Issue by gipert** [bat/bat#265]
Given that I manually compiled and installed Cuba, I'm experiencing the following issue on OSX:
```
$ ./configure --with-cuba --enable-parallel
[...]
checking for cuba.h in system default directories
checking cuba.h usability... yes
checking cuba.h presence... yes
checking for cuba.h... yes
checking for cuba library in system default directories
detected cuba matching the interface of version 4.1
checking for main in -lcuba... no
configure: error: Could not find libcuba.a; use --with-cuba-lib-dir=DIR or compile without cuba
```
```
$ ./configure --with-cuba
[...]
checking for cuba.h in system default directories
checking cuba.h usability... yes
checking cuba.h presence... yes
checking for cuba.h... yes
checking for cuba library in system default directories
detected cuba matching the interface of version 4.1
checking for main in -lcuba... yes
[...]
```
I also tried to manually specify the path to `libcuba.a`, no luck. Can you reproduce the issue?

**Comment by gipert** [comment]
Tried pretty everything, it does not work neither with `--with-cuba=download`. Seems to be a OSX issue, I'm not an expert of autotools but I'll try to figure out why

**Comment by gipert** [comment]
I think I got it by looking at the logs... Clang does not support OpenMP naively so something happens when looking for Cuba, as the configure script does not check if the compiler supports the `-fopenmp` flag. It's a minor issue, but maybe you should add this check for OSX users that try to build bat with the built-in clang :)

**Comment by fredRos** [comment]
Ok, you are right. This is an issue we have to fix
