### ISSUE TITLE
[cling] annoying error: headers not found

### ISSUE THREAD

**Issue by gipert** [bat/bat#269]
Another little issue...

As you may know Cling shipped with recent ROOT versions complains about not finding headers runtime.
```
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for .includes/BAT/BCObservable.h
   requested to autoload type BCVariableSet
```
Normally one would have to update `ROOT_INCLUDE_PATH`, however the path that the error cites (`.includes/BAT/`) does not exists, so currently the only workaround one can adopt is:
```shell
ln -s `bat-config --prefix`/include `bat-config --prefix`/.includes
export ROOT_INCLUDE_PATH=$ROOT_INCLUDE_PATH:`bat-config --prefix`
```

Hopefully this should be really a 5 minutes fix...

**Comment by oschulz** [comment]
I wasn't able to reproduce this (on Linux, ROOT v6.12.06). After installing BAT, setting PATH and LD_LIBRARY_PATH was sufficient to run the graphFitter Example in ROOT (via Cling) and to compile and run the binomial example (via GCC).

@gipert, could you generate a minimal test case that produces the autoloading failure?

**Comment by gipert** [comment]
It happens really with *any* executable linked with the BAT libraries. It happens also with all the other GERDA software... unless I set `ROOT_INCLUDE_PATH`.

Running the binomial example I got as well:
```
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for .includes/BAT/BCObservable.h
   requested to autoload type BCVariableSet
```

@vonsturm can also confirm this issue

**Comment by oschulz** [comment]
That's weird - could you test with a current ROOT version (I used v6.12.06)? 

How do you install BAT, exactly?

**Comment by gipert** [comment]
Just tested with 6.12.06, same problem. I see you have an account at MPIK, there I installed BAT and ROOT using swmod under `/lfs/l2/gerda/pertoldi/swmod-bin`, if you want to take a look and test the problem. I installed BAT with `--enable-parallel` and `--with-cuba=download`

**Comment by fredRos** [comment]
I can confirm the issue on debian 9 with gcc 6.3 and ROOT 6.12.06. The binomial (compiled) and the histogramfitter (macro) examples yield the same cling error as @gipert reported above. This may be due to a recent change when @greenwald and I removed memory leaks and replace the class implementation of `BCObservableSet` by `typedef BCVariableSet<BCObservable> BCObservableSet;`

**Comment by oschulz** [comment]
Good catch!
