### ISSUE TITLE
Print only 1D knowledge-update plots

### ISSUE THREAD

**Issue by gipert** [bat/bat#300]
I think it would be very nice to add a flag to `BCModel::PrintKnowledgeUpdatePlots` to let it only draw 1D plots, with a high number of parameters it takes really a lot of CPU time and quite often the user is not really interested in 2D plots (maybe in a second moment).

**Comment by greenwald** [comment]
Hello @gipert, you may achieve this already via `BCEngineMCMC::SetFlagFillHistograms(true, false)`. This will also save the memory space by not even creating the 2D histograms.

**Comment by gipert** [comment]
Nice! I didn't spot it by looking into the source. Maybe it would be nice to highlight this in the docs.

@vonsturm @ThWester @annkasch did you know that?
