### ISSUE TITLE
./autogen.sh fails on fedora 28

### ISSUE THREAD

**Issue by tquante** [bat/bat#311]
Dear Developers,

I tried to update the bat version to 1.0 but unfortunately 
on Fedora 28 ./autogen.sh fails with the following error message:

aclocal: warning: couldn't open directory 'm4': No such file or directory
doc/manual/Makefile.am:77: warning: call extract_page, 1, $?, $@: non-POSIX variable name
doc/manual/Makefile.am:77: (probably a GNU make extension)
doc/manual/Makefile.am:79: warning: call extract_page, 1, $?, $@: non-POSIX variable name
doc/manual/Makefile.am:79: (probably a GNU make extension)
doc/manual/Makefile.am:81: warning: call extract_page, 3, $?, $@: non-POSIX variable name
doc/manual/Makefile.am:81: (probably a GNU make extension)
doc/manual/Makefile.am:83: warning: call extract_page, 1, $?, $@: non-POSIX variable name
doc/manual/Makefile.am:83: (probably a GNU make extension)
doc/manual/Makefile.am:96: warning: '%'-style pattern rules are a GNU make extension
doc/manual/Makefile.am:97: warning: basename $@: non-POSIX variable name
doc/manual/Makefile.am:97: (probably a GNU make extension)
models/base/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
models/base/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
models/base/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
models/base/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
models/base/Makefile.am:6:   its definition is in aclocal's search path.
models/mtf/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
models/mtf/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
models/mtf/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
models/mtf/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
models/mtf/Makefile.am:6:   its definition is in aclocal's search path.
src/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:6:   its definition is in aclocal's search path.
test/Makefile.am:14: error: library used but 'RANLIB' is undefined
test/Makefile.am:14:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
test/Makefile.am:14:   to 'configure.ac' and run 'autoconf' again.
autoreconf: automake failed with exit status: 1

could it be that the m4 directory, has been mistakenly removed from the repository?
Thanks for your help.

Cheers Thomas

**Comment by MooersLab** [comment]
I had the same error message on Mac Catalina (OSX 10.15.6) Xcode 11.3, but rerunning ./autogen.sh did the trick.
