### ISSUE TITLE
Execute again MarginalizeAll after unfixing parameters

### ISSUE THREAD

**Issue by rdisipio** [bat/bat#314]
Hi,

   what I want to do is to define a series of parameters, fix some of them to zero (e.g. params representing systematics), run the marginalization, unfix them, and marginalize again. I think this worked in previous versions, or if it didn't, there was no runtime error associated with it. 

What I get now (just updated to the trunk) is:

```
TypeError: none of the 2 overloaded methods succeeded. Full details:
  int BCIntegrate::MarginalizeAll() =>
    BCEngineMCMC::Metropolis: size of fMultivariateProposalFunctionCholeskyDecomposition[0] matrix does not match number of free parameters. (C++ exception of type runtime_error)
  int BCIntegrate::MarginalizeAll(BCIntegrate::BCMarginalizationMethod margmethod) =>
    takes at least 1 arguments (0 given)
```

Looking inside the code, this runtime error is thrown by BCEngineMCMC

```
   // check that correct objects of correct size have been created
    // these checks will fail if the user has changed the number of chains or parameters
    // or the fixing of parameters between the pre-run and the main run, or between main runs
    if (fMCMCStatistics.size() != fMCMCNChains)
        throw std::runtime_error("BCEngineMCMC::Metropolis: size of fMCMCStatistics does not match number of chains.");
...blablabla..
for (unsigned c = 0; c < fMultivariateProposalFunctionCholeskyDecomposition.size(); ++c)
            if (fMultivariateProposalFunctionCholeskyDecomposition[c].GetNrows() != static_cast<int>(GetNFreeParameters()) or
                    fMultivariateProposalFunctionCholeskyDecomposition[c].GetNcols() != static_cast<int>(GetNFreeParameters()))
                throw std::runtime_error(Form("BCEngineMCMC::Metropolis: size of fMultivariateProposalFunctionCholeskyDecomposition[%u] matrix does not match number of free parameters.", c));
```

which is exactly what I'm trying to do. Is there a neat way to fix this problem? Or do I have to create another instance of the model with the full list of parameters? But then, what's the purpose of fixing/unfixing parameters if one can not re-run the marginalization?

Cheers,
Riccardo

**Comment by oschulz** [comment]
This should work, of course - @fredRos , @greenwald , did something change here on the way to 1.0?

Yes, try creating a new instance of the model, as a workaround.

**Comment by oschulz** [comment]
In that case, it's probably best if you use a new model instance for each run, that should give you the most stability. If your model constructor doesn't, for some reason, do some very expensive calculations, there should be no real run time cost to this (as sampling will, of course, typically run much longer than model instantiation).

**Comment by greenwald** [comment]
Hello @rdisipio, in adding the ability to marginalize further, we changed the semantics of how marginalization is run.

When you call `Marginalize()` on a fresh model, it will run the pre-run and the main run. When you call `Marginalize()` again, it will continue the main run for more iterations. If you have changed the model (fixing a parameter is a change of model), then the main run cannot cleanly continue running and you will get an error.

If you want to start fresh after making a change to the model, you need to tell BAT to rerun the pre-run with `SetFlagPreRun(true)`.
