### ISSUE TITLE
conflict between math.h and cmath

### ISSUE THREAD

**Issue by talismanbrandi** [bat/bat#318]
https://github.com/bat/bat/blob/f919cafbc02df5e6dba748efb5fca881f9b0a293/src/BCMath.cxx#L21

Hi,

TMath.h contains an inclusion of cmath. Including math.h after including TMath.h seems unnecessary. Also, it creates an error with some compilers, e.g. GCC 7.3.0.

In file included from BCMath.cxx:21:0:
/Users/ayanpaul/opt/local/include/c++/7.3.0/math.h:66:12: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
 using std::isnan;
            ^~~~~
In file included from BCMath.cxx:17:0:
/Users/ayanpaul/opt/local/include/TMath.h:407:19: note: previous declaration ‘int isnan(double)’
        extern int isnan(double);

The code compiles just fine without the inclusion of math.h.

thanks! 
Ayan

**Comment by oschulz** [comment]
Thanks for reporting this! We should indeed `#include <cmath>`. It should be included explicitly though, we shouldn't rely on indirect includes.

**Comment by talismanbrandi** [comment]
Thanks for looking into this. Including cmath indeed solves the problem the way you want to.

**Comment by fredRos** [comment]
@oschulz Would be great to use g++7.3 in our automated testing to really make sure this problem is fixed. Who can open a PR for the fix itself?

**Comment by oschulz** [comment]
Closed by #321
