### ISSUE TITLE
Run examples

### ISSUE THREAD

**Issue by fredRos** [bat/bat#34]
For testing, it would be extremely useful to have
    make run
in `examples/` run all examples, including the root macros. This way we can make sure there are no segfaults etc.

To achieve this, we could have a common target, say `run`, in every example. Then we can recursively enter subdirectories. This new target should be added to `CreateProject.sh`

**Comment by oschulz** [comment]
Implies converting examples build to Automake.

**Comment by oschulz** [comment]
Depends on #40.
