### ISSUE TITLE
make check with threads

### ISSUE THREAD

**Issue by fredRos** [bat/bat#38]
`make check` runs much much longer with `--enable-parallelization`  than without. After 30s of using all cores, I cancel it and it stops during the `BCSummaryTool_TEST`. If I run that test individually, it finishes quickly both with `OMP_NUM_THREADS=1` and `OMP_NUM_THREADS=4`. What's going on?

**Comment by oschulz** [comment]
Seems to depend on using `make -jN`. Runs through in all cases - but with parallel make,
`BCSummaryTool_TEST` and `BCEngineMCMC_TEST` seem to interact with each other in a negative way somehow, making the tests very slow at full CPU load.

**Comment by oschulz** [comment]
Won't fix (for now at least).
