### ISSUE TITLE
Clean up trees in ROOT output

### ISSUE THREAD

**Issue by fredRos** [bat/bat#39]
the file format in root output is redundant. Let's have a tree for the
prerun and a tree for the main run. Remove phase, that's so
outdated. How can I access individual chains? Seems now they are all
merged. With separate trees per chain, could kick out iteration, too.

The format neeeds to be described properly in the manual.
@greenwald, what do you think?

**Comment by greenwald** [comment]
I don't see the reason to break up into separate trees. If you wanted to use samples from the prerun along with samples from the run, you'd need to use two trees. This would be annoying.

I am very strongly opposed to having a tree per chain. This is how it used to be. This could be useful if you wanted to do chain comparisons. But most people don't. And it made our output very cumbersome for normal usage---i.e. using the output of BAT. One needed to load each chain's tree and then fill them one by one into a histogram to contain samples from all chains. This is a great burden in the command line mode of ROOT, and fairly annoying in general.

As it stands now you can simply open the output of bat (`root output.root`) and draw all samples across all chains (`t->Draw("var")`) or limit yourself to main run (`t->Draw("var","Phase>0")`).
