### ISSUE TITLE
MCMCGetNIterationsConvergenceGlobal()

### ISSUE THREAD

**Issue by fredRos** [bat/bat#42]
`MCMCGetNIterationsConvergenceGlobal()` returns 4294967295 if BAT did not converge. Why is that? Wouldn't 0 make more sense? Because 4294967295 could be a valid number of iterations but 0 cannot. It would uniquely mean that no prerun was done

**Comment by greenwald** [comment]
This is obviously to do with an integer being returned as an unsigned number. -1 is used if convergence has not been achieved.

**Comment by fredRos** [comment]
Back to my question, why not 0 instead of -1?
Related to that: how can I find out how long the prerun was in case it converged? If it doesn't converged, it should be in `fMCMCNIterationsPreRunMax`, right?

**Comment by oschulz** [comment]
If the return type is unsigned, we should return 0 in this case. If we change it to signed, -1 would be a good choice.

**Comment by oschulz** [comment]
Fred convinced me that we should return 0 in any case, so that conversion to bool will yield `false`.

**Comment by greenwald** [comment]
The member type is int, so I changed the getter to return int. We can open a separate issue as to whether you want to change the member type to unsigned and use 0 instead of -1. I have no opinion either way.

To get the length of the pre-run you can use the std::max(this variable, pre-run min).

**Comment by greenwald** [comment]
However: I fixed the issue in question. So you I will assign changing the type to Fred, since I bet it's faster in Eclipse.

**Comment by greenwald** [comment]
if you'd like we can have a method:

    GetPreRunLength()
        { return std::min(std::max(fMCMCNIterationsConvergenceGlobal, fMCMCNIterationsPreRunMin), fMCMCNIterationsPreRunMax); }

**Comment by fredRos** [comment]
As it stands now, `fMCMCNIterationsConvergenceGlobal` is not very useful. I think we do need the function `unsigned GetNIterationsPreRun()`. It should return 0 if no prerun was performed yet, and else how long the prerun actually, regardless of whether it converged. Unfortunately it's more complicated than what @greenwald  suggested
```c++
GetPreRunLength()
    { return std::min(std::max(fMCMCNIterationsConvergenceGlobal, fMCMCNIterationsPreRunMin), fMCMCNIterationsPreRunMax); }
```
because `fMCMCNIterationsConvergenceGlobal` is not updated when the maximum number of prerun iterations is hit.
