### ISSUE TITLE
BCEfficiencyFitter : TH1I?

### ISSUE THREAD

**Issue by greenwald** [bat/bat#44]
Should BCEfficiencyFitter only accept TH1I objects? Currently it works with TH1D and always converts the bin values to int. Should we not just code it to accept only TH1I obejcts which naturally have only integer values in the bins?

**Comment by fredRos** [comment]
>From a C++ point of view, I agree. But now that's root. How often do
people use TH1I? Does it feel "unnatural" in the root world? If so, I'd
say let's stick with TH1D.

**Comment by greenwald** [comment]
OK, then I would at least change it to TH1. We should make an effort to change as many instances of TH1D and TH2D to TH1 and TH2 so that we at least aren't forcing users to use TH1D and TH2D and give them free choice.

**Comment by oschulz** [comment]
I'm also in favour of `TH1`.

**Comment by greenwald** [comment]
Transfering to new issue #61
