### ISSUE TITLE
Example precisions

### ISSUE THREAD

**Issue by greenwald** [bat/bat#47]
Most examples are set for a Medium precision, which means 5 chains running 100k samples each. I think this is excessive for demonstrating to users functionality. I suggest instead Quick precision (2 chains with 10k samples each), followed by setting the number of chains to 3. I have done this already in the ROOT macro examples (it was especially necessary in the advanced example, which compares four models!).

**Comment by fredRos** [comment]
I agree, we want the examples to run faster. I'm facing the same problem in the performance test suite, in which I wonder why so many evaluations are done.

**Comment by greenwald** [comment]
Some examples run acceptably fast with Medium precision. (For example: basic/errorpropagation.) Do we want to leave them as is?

**Comment by fredRos** [comment]
Why 3 chains instead of 2? The point is that examples should be quick unless the point is that they take long. If output is fine, then I'm all for quick settings. But if medium feels good enough, then just leave it because in a real application, users typically want more safety to be sure.

**Comment by greenwald** [comment]
We can also just use two chains.
