### ISSUE TITLE
Replace get-cuba.sh by configure option --with-cuba=download

### ISSUE THREAD

**Issue by oschulz** [bat/bat#49]
* More user-friendly

* Enables us to use Autotools for directory resolution (e.g. to find "cuba-version.txt"). `get-cuba.sh` in it's current form does not work for out-of-tree builds.

**Comment by fredRos** [comment]
Sounds good, I promise to rate your pull request positively :)

**Comment by greenwald** [comment]
What about telling config where to install CUBA? I used your get-cuba.sh script (which worked great), but didn't want to leave CUBA in the ROOT directory and moved it. I'm sure others would like that as well.

**Comment by oschulz** [comment]
> What about telling config where to install CUBA? I used your get-cuba.sh script (which worked great), but didn't want to leave CUBA in the BAT directory and moved it. I'm sure others would like that as well.

This is intended as a simple, fully automatic solution, especially for new users and automatic testing. The location of the cuba dir therefore doesn't matter, the user shouldn't need to worry about it. This a throw-away cuba build (to be cleaned up by `make distclean` for the planned `./configure --with-cuba=download`. It should therefore always reside in the current build directory.

**Comment by greenwald** [comment]
OK. Can we also use bat-config to return the location of the cuba installation?

**Comment by fredRos** [comment]
I think we could but how useful is it? The point is that the cuba code is statically linked so it is included in `libBAT.so`. So after building, the cuba installation is completely unneeded. And in any case, it would only stay in the build directory, and no cuba file is copied to `PREFIX`.
If a user wants to install cuba properly, she can do so. For us, we should strive to hide cuba

**Comment by oschulz** [comment]
> OK. Can we also use bat-config to return the location of the cuba installation?

No - the whole point of this automatic Cuba download is that we do *not* refer to cuba in the BAT headers or libraries (since Cuba is linked statically). The downloaded Cuba is supposed to be temporary, so it *must not* appear in the output of `bat-config`.

**Comment by greenwald** [comment]
So what would the CXXFLAGS look like when one uses CUBA? Currently the examples, with CUBA enabled, include:

    CXXFLAGS = ... -I/path/to/cuba
    LDFLAGS = ... -L/path/to/cuba

**Comment by oschulz** [comment]
The BAT user doesn't need to give any path to CUBA, 'cause it's statically linked into BAT.

**Comment by greenwald** [comment]
OK. Then make sure this is compatible with how the setting of the variables I mentioned above. That is: if CUBA is statically linked in, it should not appear in the CXX and LD flags.

**Comment by oschulz** [comment]
Yes, I'll try to get rid of that.

**Comment by fredRos** [comment]
This issue was in part motivated by a user who didn't succeed in compiling cuba on a mac. This user had qt development libraries installed, and cuba failed because of that. While this is no fault of bat itself, we also don't want to cause unnecessary trouble to users. What we need is the cuba library, so we should build just that with `make lib` as suggested by the cuba author. A side effect is that the build time is reduced. I attach a pull request
