### ISSUE TITLE
Allocate TVectorD only once

### ISSUE THREAD

**Issue by fredRos** [bat/bat#63]
Browsing the code, I stumbled on this line
https://github.com/bat/bat/blob/master/src/BCEngineMCMC.cxx#L1408

```cpp
bool BCEngineMCMC::MCMCGetProposalPointMetropolis(unsigned chain, std::vector<double>& x)
{
    x = fMCMCx[chain];

    // generate N-Free N(0,1) random values
    TVectorD y(GetNFreeParameters());
...
}
```
@greenwald, is there any good reason to allocate a new `TVectorD` in every iteration? I guess not and suggest we allocate this once in `MCMCInitialize`

**Comment by greenwald** [comment]
Nope. Feel free to optimize.
