### ISSUE TITLE
Remarginalize: tree output variables

### ISSUE THREAD

**Issue by fredRos** [bat/bat#64]
@greenwald: In `BCEngineMCMC::Remarginalize` https://github.com/bat/bat/blob/master/src/BCEngineMCMC.cxx#L1151 and below,
* why is phase from tree linked directly to `fMCMCPhase` but the others link to `fMCMCTree_*`?
* why is LogProbability linked to `fMCMCTree_Prob` and not `fMCMCTree_LogProb`?

Overall, why did you replicate many of the variables but not all? My first guess would be not to replicate anything at all. Was there a problem with it?

**Just a reminder to myself: if we change the variables, we may have to update `parallel_TEST` again.**

**Comment by greenwald** [comment]
To be able to load entry by entry from the tree, as required by how ROOT `TTree`'s operate yet also accommodating that BAT expects to fill each chain's parameter set into a single 2D vector (first index being for the chain, second for the parameter).

**Comment by fredRos** [comment]
OK, got it!
