### ISSUE TITLE
Enable roostats by default if available

### ISSUE THREAD

**Issue by fredRos** [bat/bat#76]
Keep configure option alive if user wants to explicitly enable or disable

**Comment by greenwald** [comment]
We are now getting a Roostats initialization message at startup, even if
Roostats is not directly used. Can we suppress this?

Daniel

On Wed, Sep 23, 2015, 00:08 Oliver Schulz <notifications@github.com> wrote:

> Closed #76 <https://github.com/bat/bat/issues/76> via #87
> <https://github.com/bat/bat/pull/87>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bat/bat/issues/76#event-416403153>.
>
-- 
------------------------------------------------
Daniel Greenwald
Physik-Department E18
Technische Universität München
James-Franck-Str. 1
85748 Garching
Germany

daniel.greenwald@tum.de
tel   :  +49 89 / 289 12569
fax  :  +49 89 / 289 12570

**Comment by fredRos** [comment]
Ok, @greenwald and I discussed and I agree this startup message is really annoying. In addition, I think most users don't use roostats but roostats is in the default root binaries. I would like to avoid the user being spammed, so I will revert to disable roostats by default
