### ISSUE TITLE
reference counting example

### ISSUE THREAD

**Issue by fredRos** [bat/bat#78]
The example "advanced/referenceCounting" takes a long time to run, is there some way to cut it down a bit?

**Comment by greenwald** [comment]
I looked into it and cut it down as much as I could without too much
thought. The reference prior is not a simple one, and can be slow. It could
potentially be sped up with some investigation of the math and some clever
programming (or an external package); but been an example, I don't think
it's worth the effort at the moment.

If we were to speed up the reference prior, we should add it to BAT itself.

On Thu, Sep 17, 2015, 11:05 Frederik Beaujean <notifications@github.com>
wrote:

> The example "advanced/referenceCounting" takes a long time to run, is
> there some way to cut it down a bit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bat/bat/issues/78>.
>
-- 
------------------------------------------------
Daniel Greenwald
Physik-Department E18
Technische Universität München
James-Franck-Str. 1
85748 Garching
Germany

daniel.greenwald@tum.de
tel   :  +49 89 / 289 12569
fax  :  +49 89 / 289 12570

**Comment by fredRos** [comment]
I improved it dramatically in #98 . The point was to take an approximation to the analytical result which was offered but commented out.
