### ISSUE TITLE
Integration method

### ISSUE THREAD

**Issue by fredRos** [bat/bat#79]
Sample output of Polynomial fit example

    Summary : Running normalization of all models.
    Summary : Integrate using Grid
    Summary :  --> Target relative precision:    1.000000e-02
    Summary :  --> Target absolute precision:    1.000000e-06
    Summary :  --> Result of integration:        1.162480e-05 +- -1.000000e+00
    Summary :  --> Obtained relative precision:  -1.000000e+00.
    Summary : Integrate using Cuba
    Summary :  --> Target relative precision:    1.000000e-02
    Summary :  --> Target absolute precision:    1.000000e-06
    Summary :  --> Result of integration:        7.507787e-03 +- 7.305431e-05
    Summary :  --> Obtained relative precision:  9.730472e-03.
    Summary :  --> Number of iterations:         232000

Why 2D done with grid? Why no precision? Why not number of iterations reported for grid?

**Comment by greenwald** [comment]
We have a default that a 2D problem is attacked with gridding. I'm all for removing that, since I don't see BAT as a generic tool. I think people use it expecting MCMC. Other methods should not be defaults.

My guess is that with gridding we don't store any of the intermediate output for calculating the precision of the whole calculation, nor even the number of iterations. This shouldn't be hard to implement.

**Comment by fredRos** [comment]
No this is different. It is not about marginalizing a 2D function but about computing the evidence in 2D. I'm fine with the grid for marginals, it's fast and much more robust than MCMC. But I don't see why a grid is used for the evidence.

**Comment by fredRos** [comment]
I had a look again at the code, I think @greenwald wrote this a while ago. The documentation of the method `BCIntegrate::IntegrateSlice` is scarce at best. In the end, it's just discretizing on a grid I guess. 
A few comments:

1. There is no problem counting the number of posterior evaluations and printing it like for the other methods.
2. Estimating the uncertainty is a another story, and we can leave this for the future but I think it's not too important.
3. Inside [`BCIntegrate::Integrate`](https://github.com/bat/bat/blob/master/src/BCIntegrate.cxx#L332) it says it only works with 2 dimensions. But in [`BCIntegrate::GetSlice`]( https://github.com/bat/bat/blob/master/src/BCIntegrate.cxx#L815), it says it works up to 3 dimensions. So should we enable it up to 3 dimension then?
4. In [`BCIntegrate::IntegrateSlice`](https://github.com/bat/bat/blob/master/src/BCIntegrate.cxx#L1877), the integral is estimaded by multiplying with the maximum value of the posterior. Isn't that an unnecessarily rough estimate?
5. Min and max are recorded in [`BCIntegrate::GetSlice`]( https://github.com/bat/bat/blob/master/src/BCIntegrate.cxx#L941). The min isn't used at all, max for the estimate (see previous point). We could record them for optimization, too.

I vote for preferring cuba by default if it's available. In that case in low dimension <= 3, cuhre should perform most reliably and with the least number of posterior evaluations. Otherwise the grid seems to be a decent alternative.

**Comment by fredRos** [comment]
I looked into the polynomial fit problem again. There is a 2D and a 3D integral. 

I start with the 3D problem: vegas and suave gave intervals that were totally off for 1 % and 0.1 % precision. So we should definitely remove vegas as the default cuba method. Even cuhre was off for 1% but then homed in at higher precision. Divonne was most reliable and needed similar number of calls as cuhre for 1% and 0.1%. If you need higher precision than that, cuhre is the clear champion in 3 dimensions as divonne needs ~ 3 as many evaluation as cuhre to reach claimed accuracy of 0.01 %.

The  2D problems seems simpler, all methods agree at 1% accuracy except cuhre that again prematurely converges. Again, at 0.1 and below, cuhre is best and agrees with divonne but divonne needs many more iterations, and vegas and suave need many many more.

The grid method doesn't estimate the accuracy so it always gives the same result. In 2D it agrees with divonne but needs less iterations at 0.1 % given the default 100 bins per parameter resulting in 100^2 iterations. 

Here are my recommendations, please comment:

1. I vote for preferring cuba by default if it's available.
2. Vegas should not be the default anymore.
3. With cuba in low dimension <= 3, divonne seems the best choice for our standard of 1 % accuracy. We should explain that if more is needed, cuhre is preferable. When we set the default, we can do this comparison ourselves. I'm not sure what to do for higher dimensional problems but I'm inclined to stick with divonne. cuhre will definitely explode in computational costs in more than 3D.
4. The grid seems to be a decent alternative in 2D.

**Comment by oschulz** [comment]
Passes `make distcheck` on Linux and OS-X, ROOT-5 and ROOT-6.
