### ISSUE TITLE
Tests fail after merging #72

### ISSUE THREAD

**Issue by oschulz** [bat/bat#81]
After merging #72 with master at least the efficiencyFitter example (probably others too) fails on Linux and on OS-X with ROOT-6 (with ROOT-5, all is fine). Tested with master at commit 054efb2.

Linux:

    ./autogen.sh && ./configure && DISTCHECK_CONFIGURE_FLAGS="--enable-roostats --enable-parallelization --with-cuba=download" make -j8 distcheck
OS-X:

    ./autogen.sh && ./configure && DISTCHECK_CONFIGURE_FLAGS="--enable-roostats --with-cuba=download" make -j4 distcheck

**Comment by oschulz** [comment]
After merging with #74, the problem persists. Failure was only observed consistently on Linux, no longer on OS-X - but due to the nature of segfaults, that doesn't have to mean anything.

**Comment by fredRos** [comment]
Which failures do you observe? Please post the stack trace if possible. To avoid double posting, I just refer to my latest comments in #74. The error only appears with the fast fitters and multiple threads. That's why you don't see it appear in your tests on OS X. Seems to be a root issue...

**Comment by fredRos** [comment]
I found the origin of the problem: a new member was added to TF1 and not copied in the cop constructor. I submitted a bug report https://sft.its.cern.ch/jira/browse/ROOT-7672 and included a workaround in bat. `make check` passes with multiple threads and the latest root 6.05.02 on my debian machine.

**Comment by fredRos** [comment]
Just for the record: I remove the fix to make the code cleaner and we don't support root 6.05. Use 6.04.10 or 6.06 and higher.

In case this helps a search engine, symptoms are: fast fitter examples are very slow because on every evaluation, the normalization is recalculated. With multiple threads, this integration fails because apparently TF1 is not thread safe in this regard. 

I get various error messages when running `make  -C examples/advanced/advancedGraphFitter/ check`. For example
```
Summary : Pre-run Metropolis MCMC for model "f2" ...
Error in <GSLError>: Error 11 in /mnt/vdb/lsf/workspace/root-release-6.04/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.05.02-cmake/GSL-prefix/src/GSL/integration/qags.c at 543 : number of iterations was insufficient
Warning in <TF1::IntegralOneDim>: Error found in integrating function f2 in [0.000000,100.000000] using AdaptiveSingular. Result = -nan +/- nan  - status = 11
Error in <GSLError>: Error 11 in /mnt/vdb/lsf/workspace/root-release-6.04/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/build/root_v6.05.02-cmake/GSL-prefix/src/GSL/integration/qags.c at 543 : number of iterations was insufficient
Warning in <TF1::IntegralOneDim>: Error found in integrating function f2 in [0.000000,100.000000] using AdaptiveSingular. Result = -nan +/- nan  - status = 11
Function Parameters = { A_gauss=0 mean=0 sigma=0 offset=0 }
Function Parameters = { A_gauss=0 mean=0 sigma=0 offset=0 }
Summary :  --> Perform MCMC pre-run with 2 chains, each with maximum 10000 iterations

 *** Break *** segmentation violation
```
