### ISSUE TITLE
User actions & proper handling of current chain number

### ISSUE THREAD

**Issue by greenwald** [bat/bat#82]
We should check that we provide access in all the proper spots for user actions:

* At initialization
* Before and after pre-run
* Before and after main run
* before and after point proposal
* before and after new point

(These can be debated, but we should make sure we provide robust access that doesn't slow us down.)

Alongside this, I think we need to append the current chain number to the arguments of many such functions (including the LogLikelihood and LogAPrioriPrior calls), since as it is now, it's not thread safe with our parallelization.

**Comment by greenwald** [comment]
As discussed we will use a method to return current chain in a threadsafe way (assigned to Fred).

**Comment by fredRos** [comment]
I disagree that we should attach the chain number to the interface as that is to major a change. I implemented `MCMCGetCurrentChain` to do what we want in c5997d5. It worked well in the `BCFitter` classes that fully use this feature starting from  #98.

At the moment I don't think we should add all these hooks, so I close the issue
