### ISSUE TITLE
Segfault/ out of range exception when using MCMCUserInterface [Master Branch]

### ISSUE THREAD

**Issue by tquante** [bat/bat#91]
Dear developers,

I have found a bug in the BCEngineMCMC. If you use the MCMCUserInterface you have access to the function MCMCx(int chain), which returns the current values of all parameters. In case the MCMCInititialze() fails the fMCMCx vector is cleared, which lead to an  out_of_range exception if you access it via the MCMCx(int chain) method. If the interface code is needed I can provide it via mail.
Regards

Thomas

**Comment by oschulz** [comment]
Here's the file from Thomas:

[MCMCUserInterface.txt](https://github.com/bat/bat/files/26156/MCMCUserInterface.txt)

Any ideas?

**Comment by fredRos** [comment]
Dear Thomas,

seems the compiler is too generous. The method in question is declared as 

```c++
virtual bool MCMCUserInitialize() { return true; }
```

If your implementation fails and doesn't return anything, then we can't know that. Just add `return false;` where needed and the program should stop.

**Comment by tquante** [comment]
Ok I think this will help. Another problem i forgot to mention is that 

	MCMCGetNChains();
	fMCMCx.size()

will not return the same value in case the MCMCInitialize() not MCMCUserInitialize() will fail, because the chain vector is cleared and in the version I use the MCMCx(int chain) method did not catch that case.

**Comment by fredRos** [comment]
Ok, clearly what you mention are operations on an invalid state. I changed the interface and throw exceptions now so the error can't be ignored (as was the case before). That is, the chain won't run if `MCMCInitialize()` fails. Similarly, `MCMCUserInitialize()` should throw an exception if an error is detectd. Now I know this should be done also in many other places in BAT but let's start where it's needed.
