### ISSUE TITLE
build errors due to root cflags

### ISSUE THREAD

**Issue by fredRos** [bat/bat#97]
It is dangerous to just pass through CFLAGS from root. Here is a user problem on mac os X. The user first installed gcc 5.2 via macports, probably compiled with clang++. Then he installed root and thought it was built with gcc. But apparently it was built with clang++ that passes this option `-stdlib=libc++`. But for some reason the two compilers use different names of the standard library. Then the compilation with gcc doesn't work
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -stdlib=libc++ -std=c++11 -m64 -Wall -fPIC -I../BAT -I.includes -I/opt/local/libexec/root5/include/root -O2 -Wno-unknown-pragmas -fopenmp -MT BCDataPoint.lo -MD -MP -MF .deps/BCDataPoint.Tpo -c BCDataPoint.cxx  -fno-common -DPIC -o .libs/BCDataPoint.o
g++: error: unrecognized command line option '-stdlib=libc++'
```

We have had other problems due to CFLAGS before and should strive to pass only what is needed

**Comment by fredRos** [comment]
As far as I remember, the only reason that we have
```Make
AM_CXXFLAGS = $(ROOTAUXCFLAGS) -Wall -fPIC -I$(top_srcdir)/BAT -I.includes $(ROOTCFLAGS) $(CUBAINCLUDE)
```
in `src/Makefile.am` is that we want to compile with C++11 when root 6 is used. But then we can check just for root6 in configure and add only that one flag `--std=c++11`. This would save us a lot of trouble.

**Comment by oschulz** [comment]
Hm, I don't think we can solve this: libc++ is Clang's own standard library and AFAIK it's *not* ABI compatible with GCC's libstdc++. Clang can work with both libraries, but if ROOT is built using libc++, then (to my knowlege) all other code has to be compiled that way too - meaning, it becomes incompatible with g++.

Also, in general, playing around with the CFLAGS is problematic - manipulations like that can be very fragile, and it's easy to run into trouble in some configuration that we don't normally test.

**Comment by fredRos** [comment]
> Hm, I don't think we can solve this: libc++ is Clang's own standard library and AFAIK it's not ABI compatible with GCC's libstdc++. Clang can work with both libraries, but if ROOT is built using libc++, then (to my knowlege) all other code has to be compiled that way too - meaning, it becomes incompatible with g++.

We checked this problem again, seems to be a root bug. root config returns this info based solely because it is on OS X, even if it was compiled with gcc. I will ask my colleague to file a report there.

> Also, in general, playing around with the CFLAGS is problematic - manipulations like that can be very fragile, and it's easy to run into trouble in some configuration that we don't normally test.

But why should we take over root's CFLAGS? We don't take over cuba's flags or any other dependency. The only reason I see is c++11 or not. We should control that and only that explicitly ourselves! @oschulz do you agree? Essentially this is the bottom line of #24  where root's CFLAGS also brought a user trouble

**Comment by oschulz** [comment]
Well, in general it's customary to use the flags provided by the config tools of used libs. I guess we're actually talking about `ROOTAUXCFLAGS`? On my machine, that is

    -pthread -std=c++11 -Wno-deprecated-declarations -m64

At least the `-pthread` shoudld be kept. `-m64` is not strictly necessary, I guess, but depending on the platform, there may be important flags in there. It's hard to predict without testing on every conceivable configuration. This is why I'm worried about messing with it.

**Comment by fredRos** [comment]
Hmm, I guess ideally you are right: `root-config` should provide the right flags. In practice it doesn't always but at least in this case they should fix that.

But the issue that comes up here is that `g++` and `clang++` are not 100% compatible. `g++` doesn't recognize an option known to `clang++`: `-stdlib=libc++`.
In #24, `rootcling` didn't recognize a `g++` option that was propagated from `ROOTAUXCFLAGS` and I assume `rootcling` accepts what `clang++` accepts and more. But maybe that's not even true.

I close this issue but I fear it will come back to haunt us.

**Comment by oschulz** [comment]
Well, technically it's not so much that g++ doesn't know the `-stdlib=libc++` option, but that doesn't (to my knowledge) support the new Clang standard C++ library "libc++" (which is not fully ABI compatible to "stdlibc++") at all. :-)
